# Generated by Django 3.2.9 on 2021-12-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date_pub', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image_news')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsCompetition', to='news.competition')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
